# Generated by Django 6.0.4 on 2026-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("entity_id", models.CharField(max_length=128, unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("switch", "Switch"),
                            ("light", "Light"),
                            ("climate", "Climate"),
                            ("sensor", "Sensor"),
                        ],
                        db_index=True,
                        default="switch",
                        max_length=32,
                    ),
                ),
                ("room", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("capabilities", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
