# Generated by Django 6.0.4 on 2026-04-27 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="default", max_length=64)),
                ("is_enabled", models.BooleanField(default=True)),
                ("night_start_hour", models.PositiveSmallIntegerField(default=23)),
                ("night_end_hour", models.PositiveSmallIntegerField(default=7)),
                ("min_battery_soc_night", models.FloatField(default=50.0)),
                ("min_wire_power_night", models.FloatField(default=0.0)),
                ("min_generation_power_day", models.FloatField(default=1200.0)),
                ("check_interval_seconds", models.PositiveIntegerField(default=300)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(db_index=True, default=100),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="AutomationDecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decided_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("turn_on", "Turn On"),
                            ("turn_off", "Turn Off"),
                            ("no_change", "No Change"),
                            ("skip", "Skip"),
                        ],
                        max_length=16,
                    ),
                ),
                ("should_turn_on", models.BooleanField()),
                ("mode", models.CharField(blank=True, max_length=16)),
                ("reason", models.TextField()),
                ("previous_state", models.CharField(blank=True, max_length=16)),
                ("resulting_state", models.CharField(blank=True, max_length=16)),
                ("battery_soc", models.FloatField(blank=True, null=True)),
                ("generation_power", models.FloatField(blank=True, null=True)),
                ("wire_power", models.FloatField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decision_logs",
                        to="devices.device",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decision_logs",
                        to="automation.automationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-decided_at"],
            },
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["is_enabled", "priority"], name="automation__is_enab_fe01e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationdecisionlog",
            index=models.Index(
                fields=["-decided_at"], name="automation__decided_bd12db_idx"
            ),
        ),
    ]
